#!/usr/bin/env bash
clear

set -euo pipefail
source $(dirname "$0")/sync.config.local
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Downloading database from remote server..."
echo
if [ -z "$REMOTE_SERVER" ]; then
  echo "❌ Remote server is not set. Please set the REMOTE_SERVER variable in the script."
  exit 1
fi
# Ask for database password
read -sp "Enter database password for $DATABASE_USER: " DATABASE_PASSWORD
echo
ssh -t -p2121 "$REMOTE_SERVER_USER@$REMOTE_SERVER" "\
  mysqldump -u $DATABASE_USER -p'${DATABASE_PASSWORD}' -h $DATABASE_HOST $DATABASE_NAME > ~/db_download.sql && \
  cat ~/db_download.sql && \
  rm ~/db_download.sql" > "$SCRIPT_DIR/db_download.sql"
trap 'echo "❌ Script failed on line $LINENO"' ERR

echo "✅ Database downloaded successfully."
echo "Restoring database..."
echo "Checking if local database '$LOCAL_DATABASE_NAME' exists..."
DB_EXISTS=$(mysql -u root -h $LOCAL_DATABASE_HOST -e "SHOW DATABASES LIKE '$LOCAL_DATABASE_NAME';" -s --skip-column-names)

if [ -z "$DB_EXISTS" ]; then
  echo "⚠️  Database doesn't exist. Creating..."
else
  echo "✅ Database '$LOCAL_DATABASE_NAME' already exists."
  mysqlDumpCmd=$(which mysqldump)
  backupFileName="backup_${LOCAL_DATABASE_NAME}_$(date +%s).sql"
  echo "Creating backup ${backupFileName}..."
  ${mysqlDumpCmd} -h $LOCAL_DATABASE_HOST -u root --databases $LOCAL_DATABASE_NAME > ${backupFileName}
  echo "Dropping $LOCAL_DATABASE_NAME..."
  mysql -h $LOCAL_DATABASE_HOST -u root -e "DROP DATABASE "$LOCAL_DATABASE_NAME";"
fi
mysql -u root -h $LOCAL_DATABASE_HOST -e "CREATE DATABASE \`$LOCAL_DATABASE_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -u "root" -h $LOCAL_DATABASE_HOST "$LOCAL_DATABASE_NAME" < "$SCRIPT_DIR/db_download.sql"
trap 'echo "❌ Script failed on line $LINENO"' ERR
rm "$SCRIPT_DIR/db_download.sql"
echo "✅ Database restored successfully."
