#!/usr/bin/env bash
clear
set -euo pipefail
source $(dirname "$0")/sync.config.local
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOCAL_PATH="$SCRIPT_DIR/$LOCAL_PATH"
echo "Syncing media files from remote server..."
echo
if [ -z "$REMOTE_SERVER" ]; then
  echo "❌ Remote server is not set. Please set the REMOTE_SERVER variable in the script."
  exit 1
fi
rsync -e "ssh -tt" -avz --progress -e "ssh -p 2121" "$REMOTE_SERVER_USER@$REMOTE_SERVER:$REMOTE_PATH/shared/public/media/*" "$LOCAL_PATH/"
echo "✅ Media files synced successfully."