#!/usr/bin/env bash
composer install --no-interaction
git submodule update --init --recursive
echo
yarn
cp .env .env.local
# test if var/data/addons/ydeploy exists, if not create it
if [ ! -d "var/data/addons/ydeploy" ]; then
  echo "Creating var/data/addons/ydeploy directory..."
  mkdir -p var/data/addons/ydeploy
fi
# add some line breaks
echo
echo
echo "Syncing media files and database from remote server..."
echo
read -p "Enter Remote Server User: " REMOTE_USER
read -p "Enter Remote Server Address: " REMOTE_SERVER
echo
read -p "Enter Remote Database Host: " DATABASE_HOST
read -p "Enter Remote Database Name: " DATABASE_NAME
read -p "Enter Remote Database User: " DATABASE_USER
read -p "Enter Local Database Host: " LOCAL_DATABASE_HOST
read -p "Enter Local Database Name: " LOCAL_DATABASE_NAME
echo
# check if sync.config.local exists
if [ -f "sync.config.local" ]; then
  echo "sync.config.local already exists. Skipping creation."
else
  echo "Creating sync.config.local..."
  CONTENT='REMOTE_SERVER_USER="'${REMOTE_USER}'"
REMOTE_SERVER="'${REMOTE_SERVER}'"
REMOTE_PATH="~/httpdocs/shared/public/media"
LOCAL_PATH="public/media"
DATABASE_HOST="'${DATABASE_HOST}'"
DATABASE_NAME="'${DATABASE_NAME}'"
DATABASE_USER="'${DATABASE_USER}'"
LOCAL_DATABASE_HOST="'${LOCAL_DATABASE_HOST}'"
LOCAL_DATABASE_NAME="'${LOCAL_DATABASE_NAME}'"';
  touch sync.config.local
  echo "$CONTENT" >> "sync.config.local"
fi
