#!/usr/bin/env bash

installedRepos=()

installRepositories() (
    set -eu
    local user="$1"  
    shift
    local repos="$@"

    for repo in ${repos[@]}
    do
        set -eu
        printf "Loading: ${user}/${repo}\n"
        local tmpdir=$(mktemp -d)
        trap 'rm -rf -- "$tmpdir"' EXIT    
        local url="https://api.github.com/repos/${user}/${repo}"
        local repoNormalized=`echo ${repo} | sed 's/\//-/g'`
        curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}
        local json_data=(`php -r '$data = json_decode(file_get_contents("'${tmpdir}'/'${repo}'_repo.json")); echo $data->name . " " . $data->releases;'`)
        local name="${json_data[0]}"
        local releases="${json_data[1]}"
        if [ -z "$releases" ]; then
            curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}/releases/latest
            zipball_url=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->zipball_url;"`
        else
            default_branch=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->default_branch;"`
            zipball_url="${url}/zipball/${default_branch}"
        fi
        rm -rf ${tmpdir}/*
        curl -Ls -o ${tmpdir}/${repoNormalized}.zip ${zipball_url}

        unzip -oq ${tmpdir}/${repoNormalized}.zip -d ${tmpdir}/unzip
        local files=("$tmpdir"/unzip/*)
        mkdir -p ./src/addons/${repoNormalized}/
        mv "$files"/* ./src/addons/${repoNormalized}/;

        printf "${CGREEN}${repo}${CNO} was successful loaded and unzipped into the addon folder\n\n"
        installedRepos+=("${name}")

        sleep .1 # Waits 0.1 seconds.

    done

)

resetsetup

set -e
CRED='\033[0;31m'
CGREEN='\033[0;32m'
CNO='\033[0m' # No Color


echo -e "${CRED}
- - - - - - - - - - - -
Yak REDAXO Pre Setup
- - - - - - - - - - - -
${CNO}"


source $(dirname $0)/setup.cfg

echo -e "${CRED}
Reading config file
- - - - - - - - - - - -
    REDAXO install version: ${CNO}$REDAXO_VERSION${CRED}
    REDAXO shasum: ${CNO}$REDAXO_SHA${CRED}
${CNO}"

# rename env
if [ -f .env ]; then
    cp .env .env.local
    echo -e "${CGREEN}.env was copied to .env.local${CNO}"
fi

rm -rf tmp
rm -rf public

# make tmp folders
tmpdir='./tmp'
if [ ! -d ./tmp ]; then
    mkdir $tmpdir
    # mkdir ./tmp/redaxo
fi
# tmpdir=$(mktemp -dt redaxo)
trap 'rm -rf -- "$tmpdir"' EXIT


# load redaxo
echo -e "${CRED}
Load REDAXO zip file
- - - - - - - - - - - -${CNO}"
curl -Ls -o ${tmpdir}/redaxo_${REDAXO_VERSION}.zip https://github.com/redaxo/redaxo/releases/download/${REDAXO_VERSION}/redaxo_${REDAXO_VERSION}.zip
#echo `shasum -c -a 256 "${REDAXO_SHA} *.${tmpdir}/redaxo_${REDAXO_VERSION}.zip"`
echo "${REDAXO_SHA} *${tmpdir}/redaxo_${REDAXO_VERSION}.zip" | shasum -c -a 256
unzip -oq ${tmpdir}/redaxo_${REDAXO_VERSION}.zip -d ./public

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessful loaded and unzipped into the public folder"



# create Yakamara-massif file structure
echo -e "${CRED}
Create file structure
- - - - - - - - - - - -${CNO}"

rm -rf bin
rm -rf src
rm -rf var

mkdir -p bin
mkdir -p src
mkdir -p var

mv public/redaxo/bin/* bin
mv public/redaxo/cache var
mv public/redaxo/data var
mv public/redaxo/src/addons src
mv public/redaxo/src/core src
mv public/LICENSE.md LICENSE.md
rm -f public/README.md public/README.de.md
rm -f public/.htaccess

cp setup/addon.project.boot.php src/addons/project/boot.php
cp -p setup/console bin/console
cp setup/deploy.php deploy.php
cp setup/index.backend.php public/redaxo/index.php
cp setup/index.frontend.php public/index.php
cp setup/path_provider.php src/path_provider.php
cp setup/_htaccess public/.htaccess

echo -e "${CGREEN}File structure${CNO} was successful created"

# install redaxo
printf "\n\n${CRED}Installing Redaxo now
- - - - - - - - - - - -${CNO}"
php bin/console setup:run --lang --no-interaction --verbose "de_de" --agree-license --server "$REDAXO_HOST" --servername "$REDAXO_HOST_NAME" --error-email "$REDAXO_ERROR_EMAIL" --timezone "Europe/Berlin" --db-host "$REDAXO_DB_HOST" --db-login "$REDAXO_DB_USER" --db-password "$REDAXO_DB_PASSWORD" --db-name "$REDAXO_DB_NAME" --db-setup "normal" --db-createdb "yes" -db-charset "utf8mb4" --admin-username "$REDAXO_ADMIN_USERNAME" --admin-password "$REDAXO_ADMIN_PASSWORD"


# load addons
echo -e "${CRED}
Loading REDAXO packages
- - - - - - - - - - - -
${CNO}"

installRepositories "${REPOS_FOR_USER}" "${REPOS_FOR[@]}"
installRepositories "${REPOS_YAKAMARA_USER}" "${REPOS_YAKAMARA[@]}"
installRepositories "${REPOS_TBADDADE_USER}" "${REPOS_TBADDADE[@]}"

for repo in ${REPOS_OTHER[@]}
do
    set -e
    userRepo='/' read -ra ADDR <<< "$repo"
    installRepositories $userRepo[0] $userRepo[1]
done

for repo in ${REPOS_RENAME[@]}
do
    set -e
    if [ -d ./src/addons/redaxo_${repo} ]; then
        mv ./src/addons/redaxo_${repo} ./src/addons/${repo};
    fi
done

cp setup/redaxo_massif_install.sql src/addons/massif/install.sql

for repo in ${installedRepos[@]}
do
    set -e
    printf "${CGRED}Installting ${repo} ...${CNO}\n\n"
    php -r "bin/console package:install ${repo} --no-interaction --verbose"
    php -r "bin/console package:activate ${repo} --no-interaction --verbose"
    
    if([ $repo = 'bloecks' ]); then
        php -r "bin/console package:activate ${repo}/cutncopy --no-interaction --verbose"
        php -r "bin/console package:activate ${repo}/dragndrop --no-interaction --verbose"
        php -r "bin/console package:activate ${repo}/status --no-interaction --verbose"
    fi
    if([ $repo = 'ui_tools' ]); then
        php -r "bin/console package:activate ${repo}/jquery-minicolors --no-interaction --verbose"
        php -r "bin/console package:activate ${repo}/selectize --no-interaction --verbose"
    fi
    if([ $repo = 'yform' ]); then
        php -r "bin/console package:activate ${repo}/email --no-interaction --verbose"
        php -r "bin/console package:activate ${repo}/manager --no-interaction --verbose"
        php -r "bin/console package:activate ${repo}/tools --no-interaction --verbose"
    fi
done

rm -f src/addons/massif/install.sql

# remove
rm -rf public/redaxo/bin
rm -rf public/redaxo/src
rm -f public/.gitignore.example
# rm -rf setup


# execute yarn
yarn
yarn upgrade-interactive --latest

# cp setup/stylelint.config.js stylelint.config.js
# cp setup/.prettierrc.cjs .prettierrc.cjs
# cp setup/.eslintrc.cjs .eslintrc.cjs
# cp setup/.browserslistrc .browserslistrc
# cp setup/tailwind.config.js tailwind.config.js
# cp setup/postcss.config.js postcss.config.js
# cp setup/vite.config.js vite.config.js
