#!/usr/bin/env bash

installRepositories() (
    set -eu
    local user="$1"  
    shift
    local repos="$@"

    for repo in ${repos[@]}
    do
        set -eu
        printf "Loading: ${user}/${repo}\n"
        local tmpdir=$(mktemp -d)
        trap 'rm -rf -- "$tmpdir"' EXIT    
        local url="https://api.github.com/repos/${user}/${repo}"
        local repoNormalized=`echo ${repo} | sed 's/\//-/g'`
        curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}
        local json_data=(`php -r '$data = json_decode(file_get_contents("'${tmpdir}'/'${repo}'_repo.json")); echo $data->name . " " . $data->releases;'`)
        local name="${json_data[0]}"
        local releases="${json_data[1]}"
        if [ -z "$releases" ]; then
            curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}/releases/latest
            zipball_url=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->zipball_url;"`
        else
            default_branch=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->default_branch;"`
            zipball_url="${url}/zipball/${default_branch}"
        fi
        rm -rf ${tmpdir}/*
        curl -Ls -o ${tmpdir}/${repoNormalized}.zip ${zipball_url}

        unzip -oq ${tmpdir}/${repoNormalized}.zip -d ${tmpdir}/unzip
        local files=("$tmpdir"/unzip/*)
        mkdir -p ./src/addons/${repoNormalized}/
        mv "$files"/* ./src/addons/${repoNormalized}/;

        printf "${CGREEN}${repo}${CNO} was successful loaded and unzipped into the addon folder\n\n"
        sleep .25 # Waits 0.5 second.

    done

)

resetsetup

set -e
CRED='\033[0;31m'
CGREEN='\033[0;32m'
CNO='\033[0m' # No Color


echo -e "${CRED}
- - - - - - - - - - - -
Yak REDAXO Pre Setup
- - - - - - - - - - - -
${CNO}"


source $(dirname $0)/setup.cfg

echo -e "${CRED}
Reading config file
- - - - - - - - - - - -
    REDAXO install version: ${CNO}$REDAXO_VERSION${CRED}
    REDAXO shasum: ${CNO}$REDAXO_SHA${CRED}
${CNO}"

# rename env
if [ -f .env ]; then
    cp .env .env.local
    echo -e "${CGREEN}.env was copied to .env.local${CNO}"
fi

rm -rf tmp
rm -rf public

# make tmp folders
tmpdir='./tmp'
if [ ! -d ./tmp ]; then
    mkdir $tmpdir
    # mkdir ./tmp/redaxo
fi
# tmpdir=$(mktemp -dt redaxo)
trap 'rm -rf -- "$tmpdir"' EXIT


# load redaxo
echo -e "${CRED}
Load REDAXO zip file
- - - - - - - - - - - -${CNO}"
curl -Ls -o ${tmpdir}/redaxo_${REDAXO_VERSION}.zip https://github.com/redaxo/redaxo/releases/download/${REDAXO_VERSION}/redaxo_${REDAXO_VERSION}.zip
#echo `shasum -c -a 256 "${REDAXO_SHA} *.${tmpdir}/redaxo_${REDAXO_VERSION}.zip"`
echo "${REDAXO_SHA} *${tmpdir}/redaxo_${REDAXO_VERSION}.zip" | shasum -c -a 256
unzip -oq ${tmpdir}/redaxo_${REDAXO_VERSION}.zip -d ./public

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessful loaded and unzipped into the public folder"




# create Yakamara-massif file structure
echo -e "${CRED}
Create Yakamara-MASSIF file structure
- - - - - - - - - - - -${CNO}"

rm -rf bin
rm -rf src
rm -rf var

mkdir -p bin
mkdir -p src
mkdir -p var

mv public/redaxo/bin/* bin
mv public/redaxo/cache var
mv public/redaxo/data var
mv public/redaxo/src/addons src
mv public/redaxo/src/core src
mv public/LICENSE.md LICENSE.md
rm -f public/README.md public/README.de.md
rm -f public/.htaccess

cp setup/addon.project.boot.php src/addons/project/boot.php
cp -p setup/console bin/console
cp setup/deploy.php deploy.php
cp setup/index.backend.php public/redaxo/index.php
cp setup/index.frontend.php public/index.php
cp setup/path_provider.php src/path_provider.php
cp setup/_htaccess public/.htaccess

echo -e "${CGREEN}File structure${CNO} was successful created"



# load addons
echo -e "${CRED}
Loading REDAXO packages
- - - - - - - - - - - -
${CNO}"

user="FriendsOfREDAXO"
repos=("adminer bloecks developer focuspoint mblock mform quick_navigation cropper hyphenator")
installRepositories "${user}" "${repos[@]}"

user="yakamara"
repos=("redaxo_yform redaxo_yrewrite ydeploy")
installRepositories "${user}" "${repos[@]}"

user="tbaddade"
repos=("redaxo_sprog redaxo_url redaxo_watson")
installRepositories "${user}" "${repos[@]}"

installRepositories "iceman-fx" "be_tools"
installRepositories "alexplusde" "media_manager_responsive"


repos_rename=("sprog" "url" "watson" "yform" "yrewrite")

for repo in ${repos_rename[@]}
do
    set -e
    if [ -d ./src/addons/redaxo_${repo} ]; then
        mv ./src/addons/redaxo_${repo} ./src/addons/${repo};
    fi

done


# remove
rm -rf public/redaxo/bin
rm -rf public/redaxo/src
# rm -rf setup

# execute yarn
yarn
yarn upgrade-interactive --latest

cp setup/stylelint.config.js stylelint.config.js
cp setup/.prettierrc.cjs .prettierrc.cjs
cp setup/.eslintrc.cjs .eslintrc.cjs
cp setup/.browserlistrc .browserlistrc
cp setup/tailwind.config.js tailwind.config.js

