#!/usr/bin/env bash
set -e

source $(dirname $0)/setup.cfg

installRepositories() (
    set -eu
    local user="$1"  
    shift
    local repos="$@"

    for repo in ${repos[@]}
    do
        set -eu
        printf "Loading: ${user}/${repo}\n"
        local tmpdir=$(mktemp -d)
        trap 'rm -rf -- "$tmpdir"' EXIT    
        local url="https://api.github.com/repos/${user}/${repo}"
        local repoNormalized=`echo ${repo} | sed 's/\//-/g'`
        curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}
        local json_data=(`php -r '$data = json_decode(file_get_contents("'${tmpdir}'/'${repoNormalized}'_repo.json")); echo $data->name . " " . $data->releases;'`)
        local name="${json_data[0]}"
        local releases="${json_data[1]}"
        if [ -z "$releases" ]; then
            curl -Ls -o ${tmpdir}/${repoNormalized}_repo.json ${url}/releases/latest
            zipball_url=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->zipball_url;"`
        else
            default_branch=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repoNormalized}_repo.json'))->default_branch;"`
            zipball_url="${url}/zipball/${default_branch}"
        fi
        rm -rf ${tmpdir}/*
        curl -Ls -o ${tmpdir}/${repoNormalized}.zip ${zipball_url}

        unzip -oq ${tmpdir}/${repoNormalized}.zip -d ${tmpdir}/unzip
        local files=("$tmpdir"/unzip/*)
        mkdir -p ./src/addons/${repoNormalized}/
        mv "$files"/* ./src/addons/${repoNormalized}/;

        printf "${CGREEN}${repo}${CNO} was successful loaded and unzipped into the addon folder\n\n"
        installedRepos+=("${name}")

        for repoRename in ${REPOS_RENAME[@]}
        do
            set -e
            if [ -d ./src/addons/redaxo_${repoRename} ]; then
                mv ./src/addons/redaxo_${repoRename} ./src/addons/${repoRename};
            fi
        done

        printf "${CRED}Installing ${name} ...${CNO}\n\n"

        if([ $name = 'massif' ]); then
            cp "setup/redaxo_massif_install.sql" src/addons/massif/install.sql
        fi

        php bin/console package:install "${name}" --no-interaction
        php bin/console package:activate "${name}" --no-interaction
        
        if([ $name = 'bloecks' ]); then
            php bin/console package:install "${name}"/cutncopy --no-interaction
            php bin/console package:activate "${name}"/cutncopy --no-interaction

            php bin/console package:install "${name}"/dragndrop --no-interaction
            php bin/console package:activate "${name}"/dragndrop --no-interaction

            php bin/console package:install "${name}"/status --no-interaction
            php bin/console package:activate "${name}"/status --no-interaction
        fi
        if([ $name = 'ui_tools' ]); then
            php bin/console package:install "${name}"/jquery-minicolors --no-interaction
            php bin/console package:activate "${name}"/jquery-minicolors --no-interaction

            php bin/console package:install "${name}"/selectize --no-interaction
            php bin/console package:activate "${name}"/selectize --no-interaction
        fi
        if([ $name = 'yform' ]); then
            php bin/console package:install "${name}"/email --no-interaction
            php bin/console package:activate "${name}"/email --no-interaction

            php bin/console package:install "${name}"/manager --no-interaction
            php bin/console package:activate "${name}"/manager --no-interaction

            php bin/console package:install "${name}"/tools --no-interaction
            php bin/console package:activate "${name}"/tools --no-interaction
        fi
        printf "${CGREEN}${name} installed and activated!${CNO}\n\n"

        sleep .1 # Waits 0.1 seconds.

    done

)

resetsetup

CRED='\033[0;31m'
CGREEN='\033[0;32m'
CNO='\033[0m' # No Color


echo -e "${CRED}
- - - - - - - - - - - -
Yak REDAXO Pre Setup
- - - - - - - - - - - -
${CNO}"



echo -e "${CRED}
Reading config file
- - - - - - - - - - - -
    REDAXO install version: ${CNO}$REDAXO_VERSION${CRED}
    REDAXO shasum: ${CNO}$REDAXO_SHA${CRED}
${CNO}"

# rename env
if [ -f .env ]; then
    cp .env .env.local
    echo -e "${CGREEN}.env was copied to .env.local${CNO}"
    ENV_LOCAL_CONTENT='VITE_DEV_SERVER="'${VITE_DEV_SERVER}'"
VITE_DEV_SERVER_PORT="'${VITE_DEV_SERVER_PORT}'"
VITE_ENTRY_POINT="'${VITE_ENTRY_POINT}'"
VITE_PUBLIC_DIR="'${VITE_PUBLIC_DIR}'"
VITE_DIST_DIR="'${VITE_DIST_DIR}'"
MODE="development"';
    echo "$ENV_LOCAL_CONTENT" >> ".env.local"
    echo -e "${CGREEN}.env.local updated with VITE config${CNO}"

fi

rm -rf tmp
rm -rf public

# make tmp folders
tmpdir='./tmp'
if [ ! -d ./tmp ]; then
    mkdir $tmpdir
    # mkdir ./tmp/redaxo
fi
# tmpdir=$(mktemp -dt redaxo)
trap 'rm -rf -- "$tmpdir"' EXIT


# load redaxo
echo -e "${CRED}
Load REDAXO zip file
- - - - - - - - - - - -${CNO}"
curl -Ls -o ${tmpdir}/redaxo_${REDAXO_VERSION}.zip https://github.com/redaxo/redaxo/releases/download/${REDAXO_VERSION}/redaxo_${REDAXO_VERSION}.zip
#echo `shasum -c -a 256 "${REDAXO_SHA} *.${tmpdir}/redaxo_${REDAXO_VERSION}.zip"`
echo "${REDAXO_SHA} *${tmpdir}/redaxo_${REDAXO_VERSION}.zip" | shasum -c -a 256
unzip -oq ${tmpdir}/redaxo_${REDAXO_VERSION}.zip -d ./public

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessfully loaded and unzipped into the public folder"



# create Yakamara-massif file structure
echo -e "${CRED}
Creating file structure
- - - - - - - - - - - -${CNO}
"

rm -rf bin
rm -rf src
rm -rf var

mkdir -p bin
mkdir -p src
mkdir -p var

mv public/redaxo/bin/* bin
mv public/redaxo/cache var
mv public/redaxo/data var
mv public/redaxo/src/addons src
mv public/redaxo/src/core src
mv public/LICENSE.md LICENSE.md
rm -f public/README.md public/README.de.md
rm -f public/.htaccess

cp setup/addon.project.boot.php src/addons/project/boot.php
cp -p setup/console bin/console
cp setup/index.backend.php public/redaxo/index.php
cp setup/index.frontend.php public/index.php
cp setup/path_provider.php src/path_provider.php
cp setup/_htaccess public/.htaccess


echo -e "${CGREEN}File structure${CNO} was successfully created"

# install redaxo
printf "\n\n${CRED}Installing Redaxo now
- - - - - - - - - - - -${CNO}"
php bin/console setup:run --lang "de_de" --agree-license --server "${REDAXO_HOST_PROTOCOL}://${REDAXO_HOST_NAME}/" --servername "${REDAXO_SERVER_NAME}" --error-email "${REDAXO_ERROR_EMAIL}" --timezone "Europe/Berlin" --db-host "${REDAXO_DB_HOST}" --db-login "${REDAXO_DB_USER}" --db-password "${REDAXO_DB_PASSWORD}" --db-name "${REDAXO_DB_NAME}" --db-setup "normal" --db-createdb "yes" --db-charset "utf8mb4" --admin-username "${REDAXO_ADMIN_USERNAME}" --admin-password "${REDAXO_ADMIN_PASSWORD}" --no-interaction

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessfully installed
"


# load addons
echo -e "${CRED}
Loading REDAXO packages
- - - - - - - - - - - -
${CNO}"

installRepositories "${REPOS_YAKAMARA_USER}" "${REPOS_YAKAMARA[@]}"
installRepositories "${REPOS_FOR_USER}" "${REPOS_FOR[@]}"
installRepositories "${REPOS_TBADDADE_USER}" "${REPOS_TBADDADE[@]}"

for repo in ${REPOS_OTHER[@]}
do
    set -e
    IFS=/ read -r user repo <<< "$repo"
    installRepositories $user $repo
done


rm -f src/addons/massif/install.sql
cp -f setup/redaxo_install_config.json var/data/addons/install/config.json

php bin/console cache:clear
# remove
rm -rf public/redaxo/bin
rm -rf public/redaxo/src
rm -f public/.gitignore.example
# rm -rf setup


# execute yarn
yarn
yarn upgrade-interactive --latest

