
SET NAMES utf8mb4;

INSERT INTO `rex_article` (`pid`, `id`, `parent_id`, `name`, `catname`, `catpriority`, `startarticle`, `priority`, `path`, `status`, `template_id`, `clang_id`, `createdate`, `createuser`, `updatedate`, `updateuser`, `revision`, `yrewrite_url_type`, `yrewrite_url`, `yrewrite_redirection`, `yrewrite_title`, `yrewrite_description`, `yrewrite_image`, `yrewrite_changefreq`, `yrewrite_priority`, `yrewrite_index`, `yrewrite_canonical_url`) VALUES
(1,	1,	0,	'Home',	'Home',	1,	1,	1,	'|',	1,	1,	1,	'2024-01-11 15:21:10',	'admin',	'2024-01-11 15:21:08',	'admin',	0,	'AUTO',	'',	'',	'',	'',	'',	NULL,	NULL,	NULL,	'');

--
-- Daten für Tabelle `rex_template`
--

SET NAMES utf8mb4;

DELETE FROM `rex_template`;

INSERT INTO `rex_template` (`id`, `key`, `name`, `content`, `active`, `createdate`, `createuser`, `updatedate`, `updateuser`, `attributes`, `revision`) VALUES
(1,	'default',	'* Default',	'<?php\r\nheader(\'Content-Type: text/html; charset=utf-8\');\r\n\r\n?>\r\n<!doctype html>\r\n<html lang=\"de\">\r\n\r\n<head>\r\n	REX_TEMPLATE[key=\"html-meta\"]\r\n</head>\r\n\r\n<body class=\"bg-[#d6d8d4] font-roboto\">\r\n\r\n	REX_TEMPLATE[key=\"header\"]\r\n\r\n	<main role=\"main\" class=\"py-20 text-slate-700 leading-relaxed\">\r\n		<h1 class=\"text-3xl font-bold text-slate-800\">Yay! We are up and running 🎉</h1>\r\n		<p class=\"mt-6\">Wenn nicht bereits getan:</p>\r\n		<ol class=\"list-decimal pl-4 [&>*+*]:mt-4 mt-4\">\r\n			<li>starte im Terminal deinen Dev Server:<br />\r\n				- mit Yarn: <span class=\"inline-block bg-slate-900 text-xs font-[monospace] px-2 py-1 rounded text-emerald-400\">yarn dev</span><br />\r\n				- mit npm: <span class=\"inline-block bg-slate-900 text-xs font-[monospace] px-2 py-1 rounded text-emerald-400\">npm run dev</span><br />\r\n				- mit pnpm: <span class=\"inline-block bg-slate-900 text-xs font-[monospace] px-2 py-1 rounded text-emerald-400\">pnpm run dev</span><br />\r\n				und lade diese Seite erneut</li>\r\n			<li>melde dich im <a href=\"/redaxo/\" target=\"_blank\" class=\"underline hover:text-purple-600 transition-colors duration-300\">Redaxo Backend</a> mit folgenden Benutzerdaten an und du bist Startklar 🚀<br />{REDAXO_LOGIN_DATA}</li>\r\n			<li>Na nix!</li>\r\n		</ol>\r\n		<?php\r\n		$articleContent = $this->getArticle(1);\r\n		echo $articleContent;\r\n		?>\r\n	</main>\r\n\r\n	REX_TEMPLATE[key=\"footer\"]\r\n\r\n	REX_TEMPLATE[key=\"html-scripts\"]\r\n\r\n</body>\r\n\r\n</html>',	1,	'2024-01-09 16:13:37',	'admin',	'2025-02-28 15:37:19',	'console',	'{\"ctype\":[],\"modules\":{\"1\":{\"all\":\"1\"}},\"categories\":{\"all\":\"1\"}}',	0),
(2,	'html-scripts',	'04 - HTML Scripts',	'<?= \\Ynamite\\ViteRex\\ViteRex::getAssets() ?>',	0,	'2024-01-09 16:15:15',	'admin',	'2024-01-14 16:33:09',	'admin',	'{\"ctype\":[],\"modules\":{\"1\":{\"all\":\"1\"}},\"categories\":{\"all\":\"1\"}}',	0),
(3,	'html-meta',	'03 - HTML Meta',	'<?php\r\n$rewriter_seo = new rex_yrewrite_seo();\r\n?>\r\n\r\n<meta charset=\"utf-8\" />\r\n<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n\r\n<?= $rewriter_seo->getTags() ?>\r\n\r\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />',	0,	'2024-01-09 16:13:12',	'admin',	'2024-01-14 10:46:05',	'admin',	'{\"ctype\":[],\"modules\":{\"1\":{\"all\":\"1\"}},\"categories\":{\"all\":\"1\"}}',	0),
(4,	'footer',	'* Footer',	'<footer>\r\n</footer>',	0,	'2024-01-09 16:17:19',	'admin',	'2024-01-14 16:32:29',	'admin',	'{\"ctype\":[],\"modules\":{\"1\":{\"all\":\"1\"}},\"categories\":{\"all\":\"1\"}}',	0),
(5,	'header',	'* Header',	'<?php\r\n$nav = rex_navigation::factory();\r\n?>\r\n<header>\r\n	<div class=\"flex\">\r\n		<a href=\"<?= rex_getUrl(rex_article::getSiteStartArticleId()); ?>\" class=\"bg-gradient-to-br from-[#51bdfe] to-[#b230f2] py-3 px-6 rounded-md shadow-lg border-white text-right\">\r\n			<div class=\"text-[#fed82f] text-6xl font-bold flex\">\r\n				<span class=\"[text-shadow:_1px_2px_1px_#b230f2] -skew-x-12\">Vite</span><span class=\"text-white [text-shadow:_1px_2px_1px_#51bdfe]\">Rex</span>\r\n			</div>\r\n			<div class=\"text-white uppercase text-xs tracking-widest\"><?= rex::getServerName() ?></div>\r\n		</a>\r\n	</div>\r\n	<nav class=\"main-nav\">\r\n		<?= $nav->get(0, 1, false, true) ?>\r\n	</nav>\r\n</header>',	0,	'2024-01-09 16:18:04',	'admin',	'2025-02-28 14:52:34',	'console',	'{\"ctype\":[],\"modules\":{\"1\":{\"all\":\"1\"}},\"categories\":{\"all\":\"1\"}}',	0);