#!/usr/bin/env bash

clear
setup/resetsetup

set -e

CRED='\033[0;31m'
CGREEN='\033[0;32m'
CNO='\033[0m' # No Color

source $(dirname $0)/setup.cfg

installPackage() {
        local package="$1"  

        printf "${CRED}Installing${CNO} ${package} ...\n"

        php bin/console package:install "${package}" --no-interaction --quiet
        wait
        php bin/console package:activate "${package}" --no-interaction --quiet
        wait
        
        printf "${CGREEN}${package}${CNO} installed and activated!\n\n"
}

downloadPackageFromRepo() (
    set -eu
    local user="$1"  
    local repo="$2"

    set -eu
    printf "${CRED}Downloading${CNO} ${user}/${repo}\n"
    local tmpdir=$(mktemp -d)
    trap 'rm -rf -- "$tmpdir"' EXIT    
    local url="https://api.github.com/repos/${user}/${repo}"
    # local repoNormalized=`echo ${repo} | sed 's/\//-/g'`
    curl -Ls -o ${tmpdir}/${repo}_repo.json ${url}
    local default_branch=`php -r "echo json_decode(file_get_contents('${tmpdir}/${repo}_repo.json'))->default_branch;"`
    wait
    zipball_url="${url}/zipball/${default_branch}"
    rm -rf ${tmpdir}/*
    curl -Ls -o ${tmpdir}/${repo}.zip ${zipball_url}
    wait

    unzip -oq ${tmpdir}/${repo}.zip -d ${tmpdir}/unzip
    wait
    local files=("$tmpdir"/unzip/*)
    mkdir -p ./src/addons/${repo}/
    mv "$files"/* ./src/addons/${repo}/;

    printf "${CGREEN}${repo}${CNO} was successful loaded and unzipped into the addon folder\n"

    local name=$repo

    for repoRename in ${ADDON_REPOS_RENAME[@]}
    do
        set -e
        if [ -d ./src/addons/redaxo_${repoRename} ]; then
            mv ./src/addons/redaxo_${repoRename} ./src/addons/${repoRename};
            name=${repoRename}
        fi
    done

    installPackage "${name}"
    wait

    sleep .1 # Waits 0.1 seconds.
    wait

)


echo -e "${CRED}
- - - - - - - - - - - -
ViteRex Setup
- - - - - - - - - - - -
${CNO}"



echo -e "${CRED}
Reading config file
- - - - - - - - - - - -
    REDAXO install version: ${CNO}$REDAXO_VERSION${CRED}
    REDAXO shasum: ${CNO}$REDAXO_SHA${CRED}
${CNO}"

# rename env
# create env.local
ENV_CONTENT='VITE_DEV_SERVER="'${VITE_DEV_SERVER}'"
VITE_DEV_SERVER_PORT="'${VITE_DEV_SERVER_PORT}'"
VITE_ENTRY_POINT="'${VITE_ENTRY_POINT}'"
VITE_PUBLIC_DIR="'${VITE_PUBLIC_DIR}'"
VITE_DIST_DIR="'${VITE_DIST_DIR}'"
REDAXO_HOST_NAME="'${REDAXO_HOST_NAME}'"
MODE="development"';
touch .env.local
echo "$ENV_CONTENT" >> ".env.local"
echo -e "${CGREEN}.env.local created with VITE config${CNO}"

rm -rf tmp
rm -rf public

# make tmp folders
tmpdir='./tmp'
if [ ! -d ./tmp ]; then
    mkdir $tmpdir
    # mkdir ./tmp/redaxo
fi
# tmpdir=$(mktemp -dt redaxo)
trap 'rm -rf -- "$tmpdir"' EXIT


# load redaxo
echo -e "${CRED}
Load REDAXO zip file
- - - - - - - - - - - -${CNO}"
curl -Ls -o ${tmpdir}/redaxo_${REDAXO_VERSION}.zip https://github.com/redaxo/redaxo/releases/download/${REDAXO_VERSION}/redaxo_${REDAXO_VERSION}.zip
#echo `shasum -c -a 256 "${REDAXO_SHA} *.${tmpdir}/redaxo_${REDAXO_VERSION}.zip"`
echo "${REDAXO_SHA} *${tmpdir}/redaxo_${REDAXO_VERSION}.zip" | shasum -c -a 256
unzip -oq ${tmpdir}/redaxo_${REDAXO_VERSION}.zip -d ./public

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessfully loaded and unzipped into the public folder"



# create Yakamara-massif file structure
echo -e "${CRED}
Creating file structure
- - - - - - - - - - - -${CNO}
"

rm -rf bin
rm -rf src
rm -rf var

mkdir -p bin
mkdir -p src
mkdir -p var

mv public/redaxo/bin/* bin
mv public/redaxo/cache var
mv public/redaxo/data var
mv public/redaxo/src/addons src
cp -r setup/viterex src/addons
mv public/redaxo/src/core src
mv public/LICENSE.md LICENSE.md
rm -f public/README.md README.de.md
rm -f public/.htaccess

cp -p setup/console bin/console
cp setup/deploy.php deploy.php
cp setup/deployer.task.setup.php deployer.task.setup.php
cp setup/index.backend.php public/redaxo/index.php
cp setup/index.frontend.php public/index.php
cp setup/path_provider.php src/path_provider.php
cp setup/_htaccess public/.htaccess


echo -e "${CGREEN}File structure${CNO} was successfully created"

# install redaxo
printf "\n\n${CRED}Installing Redaxo now
- - - - - - - - - - - -${CNO}"
php bin/console setup:run --lang "de_de" --agree-license --server "${REDAXO_HOST_PROTOCOL}://${REDAXO_HOST_NAME}/" --servername "${REDAXO_SERVER_NAME}" --error-email "${REDAXO_ERROR_EMAIL}" --timezone "Europe/Berlin" --db-host "${REDAXO_DB_HOST}" --db-login "${REDAXO_DB_USER}" --db-password "${REDAXO_DB_PASSWORD}" --db-name "${REDAXO_DB_NAME}" --db-setup "normal" --db-createdb "yes" --db-charset "utf8mb4" --admin-username "${REDAXO_ADMIN_USERNAME}" --admin-password "${REDAXO_ADMIN_PASSWORD}" --quiet
wait

echo -e "${CGREEN}
Redaxo ${REDAXO_VERSION}${CNO} was sussessfully installed
"


# load addons
echo -e "${CRED}
Loading REDAXO packages
- - - - - - - - - - - -
${CNO}"

for package in ${ADDON_PACKAGES[@]}
do
    printf "\n${CRED}Downloading package${CNO} ${package}\n"
    IFS=/ read -r pckg plugin <<< "$package"
    if [ ! $plugin ]; then
        if [ ! -d ./src/addons/$pckg ]; then
            php bin/console install:download "${pckg}" --no-interaction --quiet
            wait
        fi
    fi
    installPackage "${package}" 
    wait
done

for repo in ${ADDON_REPOS[@]}
do
    set -e
    IFS=/ read -r user repo <<< "$repo"
    downloadPackageFromRepo $user $repo
    wait
done

printf "\n${CRED}Installing and activating package${CNO} ViteRex\n"
php bin/console package:install "viterex" --no-interaction --quiet

mkdir -p var/data/addons/ydeploy


php bin/console cache:clear
wait
php bin/console be_style:compile
wait

# insert redaxo_base.sql and set config
# also replace login data in default template for better DX
sed -i '' "s|{REDAXO_LOGIN_DATA}|Benutzer: ${REDAXO_ADMIN_USERNAME}<br />Passwort: ${REDAXO_ADMIN_PASSWORD}|g" setup/redaxo_base.sql
mysqlCmd=$(which mysql)
${mysqlCmd} -h ${REDAXO_DB_HOST} -u ${REDAXO_DB_USER} --password="${REDAXO_DB_PASSWORD}" --database=${REDAXO_DB_NAME} < setup/redaxo_base.sql
wait
${mysqlCmd} -h ${REDAXO_DB_HOST} -u ${REDAXO_DB_USER} --password="${REDAXO_DB_PASSWORD}" --database=${REDAXO_DB_NAME} -e "SET NAMES utf8mb4;
DELETE FROM rex_config WHERE \`namespace\` = 'phpmailer';
INSERT INTO \`rex_config\` (\`namespace\`, \`key\`, \`value\`) VALUES
('phpmailer', 'archive', 'true'),
('phpmailer', 'bcc', '\"\"'),
('phpmailer', 'charset', '\"utf-8\"'),
('phpmailer', 'confirmto', '\"\"'),
('phpmailer', 'detour_mode', 'true'),
('phpmailer', 'encoding', '\"8bit\"'),
('phpmailer', 'errormail', '0'),
('phpmailer', 'from',	'\"$MASSIF_SETTINGS_EMAIL\"'),
('phpmailer',  'fromname',	'\"$MASSIF_SETTINGS_FIRMA\"'),
('phpmailer', 'host', '\"localhost\"'),
('phpmailer', 'logging', '0'),
('phpmailer',  'mailer',	'\"mail\"'),
('phpmailer', 'password', '\"\"'),
('phpmailer', 'port', '587'),
('phpmailer', 'priority', '0'),
('phpmailer', 'security_mode', 'false'),
('phpmailer', 'smtp_debug', '\"0\"'),
('phpmailer', 'smtpauth', 'true'),
('phpmailer', 'smtpsecure', '\"tls\"'),
('phpmailer',  'test_address',	'\"studio@massif.ch\"'),
('phpmailer', 'username', '\"\"'),
('phpmailer', 'wordwrap', '120');
INSERT INTO \`rex_yrewrite_domain\` (\`id\`, \`domain\`, \`mount_id\`, \`start_id\`, \`notfound_id\`, \`clangs\`, \`clang_start\`, \`clang_start_auto\`, \`clang_start_hidden\`, \`robots\`, \`title_scheme\`, \`description\`, \`auto_redirect\`, \`auto_redirect_days\`) VALUES
(1,	'$REDAXO_HOST_PROTOCOL://$REDAXO_HOST_NAME/',	0,	1,	2,	'',	1,	0,	0,	'User-agent: *\r\nDisallow:',	'%T / %SN',	'',	1,	0);
"
wait


# remove
rm -rf public/redaxo/bin
rm -rf public/redaxo/src
rm -f public/.gitignore.example
rm -f README.md
rm -f viterex.jpg
rm -rf tmp
rm -rf .git
rm -rf setup

composer install --no-interaction --quiet

git init
git add .
git commit -m "initial commit"