package: viterex
name: ViteRex
version: '1.0.0'
author: ynamite
supportpage: https://github.com/ynamite/viterex/tree/main/setup/viterex

requires:
  redaxo: '^5.13.0'
  php:
    version: '>=7.3'

page:
  title: ViteRex
  perm: viterex[]
  icon: rex-icon fa-rocket
  subpages:
    favicon:
      title: 'Favicon'
      icon: 'fa fa-icons'
      customPage: true
      fields:
        [
          { name: 'master', label: 'Master img' },
          { name: 'name', label: 'Name' },
          {
            name: 'desktop_bg',
            label: 'Desktop background color',
            class: 'minicolors-massif'
          },
          {
            name: 'desktop_radius',
            label: 'Desktop radius',
            style: 'width: 60px'
          },
          {
            name: 'desktop_scale',
            label: 'Desktop scale',
            style: 'width: 60px'
          },
          {
            name: 'ios_bg',
            label: 'iOS background color',
            class: 'minicolors-massif'
          },
          { name: 'ios_margin', label: 'iOS margin', style: 'width: 60px' },
          {
            name: 'win_bg',
            label: 'Windows background color',
            class: 'minicolors-massif'
          },
          {
            name: 'android_margin',
            label: 'Android margin',
            style: 'width: 60px'
          },
          {
            name: 'android_bg',
            label: 'Android background color',
            class: 'minicolors-massif'
          },
          {
            name: 'android_theme',
            label: 'Android theme color',
            class: 'minicolors-massif'
          },
          {
            name: 'safari_theme',
            label: 'Safari theme color',
            class: 'minicolors-massif'
          }
        ]
